textos = {
    "seleccionar_idioma": "Selecciona el idioma",    
    "totalmente_en_desacuerdo" : "Totalmente en desacuerdo",
    "en_desacuerdo": "En desacuerdo",
    "neutral": "Neutral",
    "de_acuerdo": "En acuerdo",
    "totalmente_de_acuerdo": "Totalmente en acuerdo",
    "video_no_encontrado":"El video no se encontró en la ruta especificada.",
    "selecciona_opción": "Por favor, selecciona una opción antes de continuar.",
    "cuestionario": "Cuestionario",    
    "nombre": "Nombre:", 
    "info_personal": "Información Personal", 
    "apellido": "Apellido:", 
    "pregunta_genero": "Género:",
    "genero_opciones": ["Femenino", "Masculino", "No binario", "Prefiero no decirlo"],
    "pregunta_edad": "Edad:",
    "edad_opciones": ["Menor de 18", "18 - 24", "25 - 34", "35- 44", "55 - 64", "mayor de 64", "Prefiero no decirlo"],
    "opcion_correo": "Correo Electrónico (opcional):", 
    "boton_continuar": "Continuar", 
    "error_correo": "Por favor, ingresa un correo electrónico válido.",
    "enviado_con_éxtio": "Enviado con éxito!",
    "advertencia_faltan_datos" : "Por favor, ingresa tu nombre, apellido, género y edad. Gracias.", 
    "información_personal": "Información Personal",
    "pregunta_sector_estudio_trabajo" : "Porfavor seleccione el sector que mejor describa su trabajo o Estudios (en el caso que sea estudiante):", 
    "opciones_sector": ["Artes y Humanidades", "Negocios y Economía", "Ciencias de la Computación e Informática", "Educación", "Ingeniería y Tecnologia","Ciencias Ambientales y de la Tierra", "Salud y Medicina", "Derecho y Estudios Legales", "Ciencias de la Vida y Biología", "Matemáticas y Estadística", "Ciencias Físicas (p. ej., Física, Química)", "Ciencias Sociales", "Otros"],
    "pregunta_experiencia": "¿Cuántos años de experiéncia tiene en este ámbito?: ", 
    "opciones_experiencia": ["Menor de 1 año", "1 - 3 años", "4 - 6 años", " 7 - 10 años", "Más de 10 años"],  
    "Gracias_por_contestar_el_formulario": "Muchas gracias por contestar el formulario!",
    
    #Textos main
    "navegacion": "Navegación", 
    "selecciona_una_seccion": "Selecciona una sección:", 
    "contacto" : "Contacto", 
    "sobre_nosotros" : "Sobre Nosotros",
    "info_sobre_nosotros": "This questionnaire is part of the final project from my degree.", 
    "info_contacto": "Si deseas ponerte en contacto con nosotros, por favor completa el siguiente formulario:", 
    "correo_electronico_contacto": "Correo electrónico: ", 
    "mensaje": "Mensaje: ", 
    "enviar": "Enviar", 
    "mensaje_enviado": "¡Mensaje enviado con éxito!", 
}