import streamlit as st

textos = {
    "seleccionar_idioma": "Select Language",    
    "totalmente_en_desacuerdo": "Strongly Disagree",
    "en_desacuerdo": "Disagree",
    "neutral": "Neutral",
    "de_acuerdo": "Agree",
    "totalmente_de_acuerdo": "Strongly Agree",
    "video_no_encontrado": "The video was not found at the specified path.",
    "selecciona_opción": "Please select an option before continuing.",
    "cuestionario": "Questionnaire",    
    "nombre": "First Name:", 
    "info_personal": "Personal Information", 
    "apellido": "Last Name:", 
    "pregunta_genero": "Gender:",
    "genero_opciones": ["Female", "Male", "Non-binary", "Prefer not to say"],
    "pregunta_edad": "Age:",
    "edad_opciones": ["Under 18", "18 - 24", "25 - 34", "35 - 44", "55 - 64", "Over 64", "Prefer not to say"],
    "opcion_correo": "Email (optional):", 
    "boton_continuar": "Continue", 
    "error_correo": "Please enter a valid email address.",
    "enviado_con_éxtio": "Sent successfully!",
    "advertencia_faltan_datos": "Please enter your first name, last name, gender, and age. Thank you.", 
    "información_personal": "Personal Information",
    "pregunta_sector_estudio_trabajo": "Please select the sector that best describes your work or studies (if you are a student):", 
    "opciones_sector": ["Arts and Humanities", "Business and Economics", "Computer Science and IT", "Education", "Engineering and Technology", "Environmental and Earth Sciences", "Health and Medicine", "Law and Legal Studies", "Life Sciences and Biology", "Mathematics and Statistics", "Physical Sciences (e.g., Physics, Chemistry)", "Social Sciences", "Other"],
    "pregunta_experiencia": "How many years of experience do you have in this field?:", 
    "opciones_experiencia": ["Less than 1 year", "1 - 3 years", "4 - 6 years", "7 - 10 years", "More than 10 years"], 
    "Gracias_por_contestar_el_formulario": "Thank you so much for answering this form!",
  
    
    # Main texts
    "navegacion": "Navigation", 
    "selecciona_una_seccion": "Select a section:", 
    "contacto": "Contact", 
    "sobre_nosotros": "About Us",
    "info_sobre_nosotros": "This questionnaire is part of the final project from my degree.", 
    "info_contacto": "If you wish to contact us, please fill out the following form:", 
    "correo_electronico_contacto": "Email: ", 
    "mensaje": "Message: ", 
    "enviar": "Send", 
    "mensaje_enviado": "Message sent successfully!", 
}
